#!/bin/bash

#pgrep urxvtd;
#if [ $? = "0" ]; then
#	echo "urxvtd deamon present";
#	if [ -n "$1" ]; then
#		/usr/bin/urxvtc -e su -;
#	else
#		/usr/bin/urxvtc;
#	fi;
#else
#	echo "launching urxvtd deamon";
#	/usr/bin/urxvtd -q -o -f;
#	if [ -n "$1" ]; then
#		/usr/bin/urxvtc -e su -;
#	else
#		/usr/bin/urxvtc;
#	fi;
#fi

#echo "$@"
if [ -n "$1" ]; then
	urxvtc -e su -;
	if [ $? -eq 2 ]; then
		urxvtd -q -o -f
		urxvtc -e su -;
	fi
else
	urxvtc "$@"
	if [ $? -eq 2 ]; then
		urxvtd -q -o -f
		urxvtc "$@"
	fi
fi
